# Generated by Django 6.0.5 on 2026-05-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'dim_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimYear',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_label', models.CharField(max_length=20, unique=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactBalanceSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('borrowings', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactCashFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operating_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'fact_cash_flow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProfitLoss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('opm_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_profit_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'managed': False,
            },
        ),
    ]
